services:
    logstash:
        image: docker.elastic.co/logstash/logstash:8.7.1
        container_name: logstash
        volumes:
          - ./logstash/config:/usr/share/logstash/config
          - ./logstash/pipeline:/usr/share/logstash/pipeline
        ports:
          - "5044:5044"  # Port for Logstash
          - "9600:9600"  # Port for Logstash monitoring
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        environment:
            - node.name=shopdev_es
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300

    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

volumes:
    esdata:
        driver: local
